version: '3.4'

networks:
  frontend:
  backend:

services:
  mssqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ProductApi(!)
    ports:
      - "1448:1433"
    container_name: jewelssqlserver
    networks:
      - backend

  catalog:
    image: jewels/catalogapi
    build:
      context: .\ProductCatalogAPI
      dockerfile: Dockerfile
    environment:
      DatabaseServer: mssqlserver 
      DatabaseName: CatalogDbNew
      DatabaseUser: sa
      DatabasePassword: ProductApi(!)
      ExternalCatalogUrl: http://localhost:7000
    ports:
      - "7000:80" 
    container_name: jewelscatalogapi
    networks:
      - frontend
      - backend
    depends_on:
      - mssqlserver

  webmvc:
    image: jewels/webmvc
    build:
      context: .\WebMvc
      dockerfile: Dockerfile
    environment:
      CatalogUrl: http://catalog
    ports:
      - "7500:80" 
    container_name: webshop
    networks:
      - frontend
    depends_on:
      - catalog